################################
#       THIS IS THE CONFIG.    #
#  WHERE YOU CAN CONTROL THE   #
#           PLUGIN.            #
#                              #
################################

enabled: true
